// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Materialize from "../../bindings/Materialize.res.js";
import * as ReactRedux from "react-redux";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as AuthSlice from "../../features/auth/authSlice";

function login(prim) {
  return AuthSlice.login(prim);
}

function reducer(state, action) {
  if (typeof action === "object") {
    if (action.TAG === "UpdateEmail") {
      return {
        email: action._0,
        password: state.password,
        loginAttempted: state.loginAttempted
      };
    } else {
      return {
        email: state.email,
        password: action._0,
        loginAttempted: state.loginAttempted
      };
    }
  }
  switch (action) {
    case "Submit" :
      return state;
    case "LoginAttempted" :
      return {
        email: state.email,
        password: state.password,
        loginAttempted: true
      };
    case "ResetAttempt" :
      return {
        email: state.email,
        password: state.password,
        loginAttempted: false
      };
  }
}

let initialState = {
  email: "",
  password: "",
  loginAttempted: false
};

function Login(props) {
  let match = React.useReducer(reducer, initialState);
  let dispatch = match[1];
  let state = match[0];
  let reduxDispatch = ReactRedux.useDispatch();
  let navigate = ReactRouterDom.useNavigate();
  let loginError = ReactRedux.useSelector(store => store.auth.loginError);
  let token = ReactRedux.useSelector(store => store.auth.token);
  let user = ReactRedux.useSelector(store => store.auth.user);
  let session = ReactRedux.useSelector(store => store.auth.session);
  let handleSubmit = evt => {
    evt.preventDefault();
    dispatch("LoginAttempted");
    let credentials = {
      username: state.email,
      password: state.password
    };
    reduxDispatch(AuthSlice.login(credentials));
  };
  React.useEffect(() => {
    if (state.loginAttempted) {
      if (loginError !== "") {
        Materialize.showError(loginError);
        dispatch("ResetAttempt");
      }
      let loggedIn = session.loggedIn;
      if (token !== "" && loggedIn) {
        localStorage.setItem("user", token);
        let userJson = (JSON.stringify(user));
        localStorage.setItem("userInfo", userJson);
        Materialize.showSuccess("Logged in Successfully!");
        navigate("/dashboard");
        dispatch("ResetAttempt");
      }
    }
  }, [
    loginError,
    token,
    session,
    user,
    state.loginAttempted
  ]);
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("form", {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "validate",
              id: "email",
              name: "email",
              required: true,
              type: "text",
              value: state.email,
              onChange: evt => {
                let value = evt.target.value;
                dispatch({
                  TAG: "UpdateEmail",
                  _0: value
                });
              }
            }),
            JsxRuntime.jsx("label", {
              children: "Email Address",
              htmlFor: "email"
            })
          ],
          className: "input-field col s12"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "validate",
              id: "password",
              name: "password",
              required: true,
              type: "password",
              value: state.password,
              onChange: evt => {
                let value = evt.target.value;
                dispatch({
                  TAG: "UpdatePassword",
                  _0: value
                });
              }
            }),
            JsxRuntime.jsx("label", {
              children: "Password",
              htmlFor: "password"
            })
          ],
          className: "input-field col s12"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("button", {
              children: "Login",
              className: "btn waves-effect header-btn blue",
              name: "action",
              type: "submit"
            }),
            className: "container center"
          }),
          className: "col s12"
        })
      ],
      className: "col s12",
      onSubmit: handleSubmit
    }),
    className: "row"
  });
}

let make = Login;

let $$default = Login;

export {
  login,
  reducer,
  initialState,
  make,
  $$default as default,
}
/* react Not a pure module */
