// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function TestReScript(props) {
  let match = React.useState(() => 0);
  let setCount = match[1];
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h2", {
        children: "ReScript Test Component - HMR Test"
      }),
      JsxRuntime.jsx("p", {
        children: "Count: " + String(match[0])
      }),
      JsxRuntime.jsx("button", {
        children: "Increment",
        className: "btn waves-effect blue",
        onClick: param => setCount(prev => prev + 1 | 0)
      }),
      JsxRuntime.jsx("p", {
        children: "✓ ReScript compilation working!",
        className: "green-text"
      }),
      JsxRuntime.jsx("p", {
        children: "✓ Hot Module Replacement working!",
        className: "blue-text"
      })
    ],
    className: "rescript-test-component"
  });
}

let make = TestReScript;

let $$default = TestReScript;

export {
  make,
  $$default as default,
}
/* react Not a pure module */
