// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function initTooltips() {
  try {
    return (window.$('.tooltipped').tooltip());
  } catch (exn) {
    return;
  }
}

function RolesAdmin(props) {
  let error = props.error;
  let loading = props.loading;
  let roles = props.roles;
  React.useEffect(() => {
    if (!loading) {
      initTooltips();
    }
  }, [loading]);
  let renderRole = role => JsxRuntime.jsxs("tr", {
    children: [
      JsxRuntime.jsx("td", {
        children: role.title
      }),
      JsxRuntime.jsx("td", {
        children: role.accessLevel.toString()
      })
    ]
  }, role._id);
  if (loading) {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Manage Roles",
            className: "header center-align"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("p", {
                children: "Loading roles...",
                className: "flow-text"
              }),
              className: "col s12 center-align"
            }),
            className: "row"
          })
        ],
        className: "card-panel"
      }),
      className: "container"
    });
  } else if (error == null) {
    if (roles == null) {
      return JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("h2", {
              children: "Manage Roles",
              className: "header center-align"
            }),
            JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("p", {
                  children: "No roles found",
                  className: "flow-text"
                }),
                className: "col s12 center-align"
              }),
              className: "row"
            })
          ],
          className: "card-panel"
        }),
        className: "container"
      });
    } else {
      return JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("h2", {
              children: "Manage Roles",
              className: "header center-align"
            }),
            JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                children: JsxRuntime.jsxs("table", {
                  children: [
                    JsxRuntime.jsx("thead", {
                      children: JsxRuntime.jsxs("tr", {
                        children: [
                          JsxRuntime.jsx("th", {
                            children: "Role"
                          }),
                          JsxRuntime.jsx("th", {
                            children: "Access Level"
                          })
                        ]
                      })
                    }),
                    JsxRuntime.jsx("tbody", {
                      children: roles.map(renderRole)
                    })
                  ],
                  className: "centered"
                }),
                className: "col s10 offset-s1 center-align"
              }),
              className: "row"
            }),
            JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("a", {
                children: JsxRuntime.jsx("i", {
                  children: "edit",
                  className: "material-icons"
                }),
                className: "btn-floating btn-large tooltipped pink",
                href: "/admin/roles/create"
              }),
              className: "fixed-action-btn",
              style: {bottom: "45px", right: "24px"}
            })
          ],
          className: "card-panel"
        }),
        className: "container"
      });
    }
  } else {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Manage Roles",
            className: "header center-align"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("p", {
                children: "Error: " + error,
                className: "flow-text red-text"
              }),
              className: "col s12 center-align"
            }),
            className: "row"
          })
        ],
        className: "card-panel"
      }),
      className: "container"
    });
  }
}

let make = RolesAdmin;

let $$default = RolesAdmin;

export {
  initTooltips,
  make,
  $$default as default,
}
/* react Not a pure module */
