// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "../../config/Api.res.js";
import * as Fetch from "../../bindings/Fetch.res.js";
import * as React from "react";
import * as RoleTypes from "../../features/roles/RoleTypes.res.js";
import * as LocalStorage from "../../bindings/LocalStorage.res.js";
import * as JsxRuntime from "react/jsx-runtime";

async function fetchRoles(token) {
  try {
    let url = Api.baseUrl + "/api/roles";
    let response = await Fetch.get(url, token);
    if (response.ok) {
      return RoleTypes.decodeRoleList(await response.json());
    } else {
      return {
        TAG: "Error",
        _0: "Failed to fetch roles: HTTP " + response.status.toString()
      };
    }
  } catch (exn) {
    return {
      TAG: "Error",
      _0: "Network error occurred"
    };
  }
}

function initTooltips() {
  try {
    return (window.$('.tooltipped').tooltip());
  } catch (exn) {
    return;
  }
}

function RolesAdmin(props) {
  let match = React.useState(() => "Loading");
  let setState = match[1];
  let state = match[0];
  React.useEffect(() => {
    let token = LocalStorage.getItemOption("user");
    if (token !== undefined) {
      let loadRoles = async () => {
        let result = await fetchRoles(token);
        if (result.TAG === "Ok") {
          let roles = result._0;
          return setState(param => ({
            TAG: "Loaded",
            _0: roles
          }));
        }
        let msg = result._0;
        return setState(param => ({
          TAG: "Error",
          _0: msg
        }));
      };
      loadRoles();
    } else {
      setState(param => ({
        TAG: "Error",
        _0: "No authentication token found"
      }));
    }
  }, []);
  React.useEffect(() => {
    initTooltips();
  }, [state]);
  let renderRole = role => JsxRuntime.jsxs("tr", {
    children: [
      JsxRuntime.jsx("td", {
        children: role.title
      }),
      JsxRuntime.jsx("td", {
        children: role.accessLevel.toString()
      })
    ]
  }, role._id);
  if (typeof state !== "object") {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Manage Roles",
            className: "header center-align"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("p", {
                children: "Loading roles...",
                className: "flow-text"
              }),
              className: "col s12 center-align"
            }),
            className: "row"
          })
        ],
        className: "card-panel"
      }),
      className: "container"
    });
  } else if (state.TAG === "Loaded") {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Manage Roles",
            className: "header center-align"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("table", {
                children: [
                  JsxRuntime.jsx("thead", {
                    children: JsxRuntime.jsxs("tr", {
                      children: [
                        JsxRuntime.jsx("th", {
                          children: "Role"
                        }),
                        JsxRuntime.jsx("th", {
                          children: "Access Level"
                        })
                      ]
                    })
                  }),
                  JsxRuntime.jsx("tbody", {
                    children: state._0.map(renderRole)
                  })
                ],
                className: "centered"
              }),
              className: "col s10 offset-s1 center-align"
            }),
            className: "row"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("a", {
              children: JsxRuntime.jsx("i", {
                children: "edit",
                className: "material-icons"
              }),
              className: "btn-floating btn-large tooltipped pink",
              href: "/admin/roles/create"
            }),
            className: "fixed-action-btn",
            style: {bottom: "45px", right: "24px"}
          })
        ],
        className: "card-panel"
      }),
      className: "container"
    });
  } else {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Manage Roles",
            className: "header center-align"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("p", {
                children: "Error: " + state._0,
                className: "flow-text red-text"
              }),
              className: "col s12 center-align"
            }),
            className: "row"
          })
        ],
        className: "card-panel"
      }),
      className: "container"
    });
  }
}

let make = RolesAdmin;

let $$default = RolesAdmin;

export {
  fetchRoles,
  initTooltips,
  make,
  $$default as default,
}
/* Api Not a pure module */
