// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";

function decodeUserName(json) {
  let obj = Stdlib_JSON.Decode.object(json);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid name object"
    };
  }
  let first = obj["first"];
  let last = obj["last"];
  if (first === undefined) {
    return {
      TAG: "Error",
      _0: "Missing name fields"
    };
  }
  if (last === undefined) {
    return {
      TAG: "Error",
      _0: "Missing name fields"
    };
  }
  let match = Stdlib_JSON.Decode.string(first);
  let match$1 = Stdlib_JSON.Decode.string(last);
  if (match !== undefined && match$1 !== undefined) {
    return {
      TAG: "Ok",
      _0: {
        first: match,
        last: match$1
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: "Invalid name fields"
    };
  }
}

function decodeUserRole(json) {
  let obj = Stdlib_JSON.Decode.object(json);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid role object"
    };
  }
  let id = obj["_id"];
  let title = obj["title"];
  let accessLevel = obj["accessLevel"];
  if (id === undefined) {
    return {
      TAG: "Error",
      _0: "Missing role fields"
    };
  }
  if (title === undefined) {
    return {
      TAG: "Error",
      _0: "Missing role fields"
    };
  }
  if (accessLevel === undefined) {
    return {
      TAG: "Error",
      _0: "Missing role fields"
    };
  }
  let match = Stdlib_JSON.Decode.string(id);
  let match$1 = Stdlib_JSON.Decode.string(title);
  let match$2 = Stdlib_JSON.Decode.float(accessLevel);
  if (match !== undefined && match$1 !== undefined && match$2 !== undefined) {
    return {
      TAG: "Ok",
      _0: {
        _id: match,
        title: match$1,
        accessLevel: match$2 | 0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: "Invalid role field types"
    };
  }
}

function decodeUser(json) {
  let obj = Stdlib_JSON.Decode.object(json);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid user object"
    };
  }
  let id = obj["_id"];
  let username = obj["username"];
  let name = obj["name"];
  let email = obj["email"];
  let role = obj["role"];
  let loggedIn = obj["loggedIn"];
  if (id === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required user fields"
    };
  }
  if (username === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required user fields"
    };
  }
  if (name === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required user fields"
    };
  }
  if (email === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required user fields"
    };
  }
  let match = Stdlib_JSON.Decode.string(id);
  let match$1 = Stdlib_JSON.Decode.string(username);
  let match$2 = decodeUserName(name);
  let match$3 = Stdlib_JSON.Decode.string(email);
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid user field types"
    };
  }
  if (match$1 === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid user field types"
    };
  }
  if (match$2.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: "Invalid user field types"
    };
  }
  if (match$3 === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid user field types"
    };
  }
  let roleOpt;
  if (role !== undefined) {
    let match$4 = Stdlib_JSON.Decode.$$null(role);
    if (match$4 !== undefined) {
      roleOpt = undefined;
    } else {
      let r = decodeUserRole(role);
      roleOpt = r.TAG === "Ok" ? r._0 : undefined;
    }
  } else {
    roleOpt = undefined;
  }
  let loggedInOpt = loggedIn !== undefined ? Stdlib_JSON.Decode.bool(loggedIn) : undefined;
  return {
    TAG: "Ok",
    _0: {
      _id: match,
      username: match$1,
      name: match$2._0,
      email: match$3,
      role: roleOpt,
      loggedIn: loggedInOpt
    }
  };
}

function decodeUsers(json) {
  let arr = Stdlib_JSON.Decode.array(json);
  if (arr === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid users array"
    };
  }
  let results = Belt_Array.map(arr, decodeUser);
  let errors = Belt_Array.keep(results, result => result.TAG !== "Ok");
  if (errors.length !== 0) {
    return {
      TAG: "Error",
      _0: "Failed to decode some users"
    };
  }
  let users = Belt_Array.keepMap(results, result => {
    if (result.TAG === "Ok") {
      return result._0;
    }
  });
  return {
    TAG: "Ok",
    _0: users
  };
}

function encodeUser(user) {
  let dict = {};
  dict["_id"] = user._id;
  dict["username"] = user.username;
  dict["email"] = user.email;
  let nameDict = {};
  nameDict["first"] = user.name.first;
  nameDict["last"] = user.name.last;
  dict["name"] = nameDict;
  let role = user.role;
  if (role !== undefined) {
    let roleDict = {};
    roleDict["_id"] = role._id;
    roleDict["title"] = role.title;
    roleDict["accessLevel"] = role.accessLevel;
    dict["role"] = roleDict;
  } else {
    dict["role"] = null;
  }
  let loggedIn = user.loggedIn;
  if (loggedIn !== undefined) {
    dict["loggedIn"] = loggedIn;
  }
  return dict;
}

function encodeLoginCredentials(credentials) {
  let dict = {};
  dict["username"] = credentials.username;
  dict["password"] = credentials.password;
  return dict;
}

function encodeSignupData(data) {
  let dict = {};
  dict["firstname"] = data.firstname;
  dict["lastname"] = data.lastname;
  dict["username"] = data.username;
  dict["email"] = data.email;
  dict["password"] = data.password;
  return dict;
}

export {
  decodeUserName,
  decodeUserRole,
  decodeUser,
  decodeUsers,
  encodeUser,
  encodeLoginCredentials,
  encodeSignupData,
}
/* No side effect */
