// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function NotFound(props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("h2", {
            children: "Not Found",
            className: "header center-align"
          }),
          className: "row"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("p", {
            children: "Sorry. This is not the page you were looking for",
            className: "flow-text center-align"
          }),
          className: "row"
        })
      ],
      className: "card-panel"
    }),
    className: "container"
  });
}

let make = NotFound;

let $$default = NotFound;

export {
  make,
  $$default as default,
}
/* react/jsx-runtime Not a pure module */
