// Generated by ReScript, PLEASE EDIT WITH CARE


function methodToString(method) {
  switch (method) {
    case "GET" :
      return "GET";
    case "POST" :
      return "POST";
    case "PUT" :
      return "PUT";
    case "DELETE" :
      return "DELETE";
    case "PATCH" :
      return "PATCH";
  }
}

function createAuthHeaders(token) {
  let headers = {};
  headers["Content-Type"] = "application/json";
  if (token !== undefined) {
    headers["x-access-token"] = token;
  }
  return headers;
}

function get(url, token) {
  return fetch(url, {
    method: "GET",
    headers: createAuthHeaders(token),
    body: undefined
  });
}

function post(url, body, token) {
  return fetch(url, {
    method: "POST",
    headers: createAuthHeaders(token),
    body: JSON.stringify(body)
  });
}

function put(url, body, token) {
  return fetch(url, {
    method: "PUT",
    headers: createAuthHeaders(token),
    body: JSON.stringify(body)
  });
}

function $$delete(url, token) {
  return fetch(url, {
    method: "DELETE",
    headers: createAuthHeaders(token),
    body: undefined
  });
}

export {
  methodToString,
  createAuthHeaders,
  get,
  post,
  put,
  $$delete,
}
/* No side effect */
