// Generated by ReScript, PLEASE EDIT WITH CARE


function getItemOption(key) {
  let value = (localStorage.getItem(key));
  if ((value === null || value === undefined)) {
    return;
  } else {
    return value;
  }
}

export {
  getItemOption,
}
/* No side effect */
