// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function getItemOption(key) {
  return Primitive_option.fromNullable(localStorage.getItem(key));
}

export {
  getItemOption,
}
/* No side effect */
