// Generated by ReScript, PLEASE EDIT WITH CARE


function showSuccess(message) {
  window.Materialize.toast(message, 2000, "success-toast");
}

function showError(message) {
  window.Materialize.toast(message, 2000, "error-toast");
}

function showInfo(message) {
  window.Materialize.toast(message, 2000, "info-toast");
}

export {
  showSuccess,
  showError,
  showInfo,
}
/* No side effect */
