// Generated by ReScript, PLEASE EDIT WITH CARE


function showSuccess(message) {
  M.toast({
    html: message,
    displayLength: 2000,
    classes: "green rounded"
  });
}

function showError(message) {
  M.toast({
    html: message,
    displayLength: 3000,
    classes: "red rounded"
  });
}

function showInfo(message) {
  M.toast({
    html: message,
    displayLength: 2000,
    classes: "blue rounded"
  });
}

export {
  showSuccess,
  showError,
  showInfo,
}
/* No side effect */
