// Generated by ReScript, PLEASE EDIT WITH CARE


function showSuccess(message) {
  window.Materialize.toast(message, 2000, "success-toast");
}

function showError(message) {
  window.Materialize.toast(message, 2000, "error-toast");
}

function showInfo(message) {
  window.Materialize.toast(message, 2000, "info-toast");
}

function initDropdown() {
  try {
    return (window.$('.dropdown-button').dropdown());
  } catch (exn) {
    return;
  }
}

function initSideNav() {
  try {
    return (window.$('.button-collapse').sideNav());
  } catch (exn) {
    return;
  }
}

function initTooltips() {
  try {
    return (window.$('.tooltipped').tooltip());
  } catch (exn) {
    return;
  }
}

export {
  showSuccess,
  showError,
  showInfo,
  initDropdown,
  initSideNav,
  initTooltips,
}
/* No side effect */
