// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.js";

function decodeDocument(json) {
  let obj = Core__JSON.Decode.object(json);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document object"
    };
  }
  let id = obj["_id"];
  let title = obj["title"];
  let content = obj["content"];
  let ownerId = obj["ownerId"];
  let role = obj["role"];
  let dateCreated = obj["dateCreated"];
  let lastModified = obj["lastModified"];
  if (id === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required document fields"
    };
  }
  if (title === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required document fields"
    };
  }
  if (ownerId === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required document fields"
    };
  }
  let match = Core__JSON.Decode.string(id);
  let match$1 = Core__JSON.Decode.string(title);
  let match$2 = Core__JSON.Decode.string(ownerId);
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document field types"
    };
  }
  if (match$1 === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document field types"
    };
  }
  if (match$2 === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document field types"
    };
  }
  let contentOpt = content !== undefined ? Core__JSON.Decode.string(content) : undefined;
  let roleOpt;
  if (role !== undefined) {
    let match$3 = Core__JSON.Decode.$$null(role);
    roleOpt = match$3 !== undefined ? undefined : Core__JSON.Decode.string(role);
  } else {
    roleOpt = undefined;
  }
  let dateCreatedOpt = dateCreated !== undefined ? Core__JSON.Decode.string(dateCreated) : undefined;
  let lastModifiedOpt = lastModified !== undefined ? Core__JSON.Decode.string(lastModified) : undefined;
  return {
    TAG: "Ok",
    _0: {
      _id: match,
      title: match$1,
      content: contentOpt,
      ownerId: match$2,
      role: roleOpt,
      dateCreated: dateCreatedOpt,
      lastModified: lastModifiedOpt
    }
  };
}

function decodeDocumentList(json) {
  let arr = Core__JSON.Decode.array(json);
  if (arr === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document list array"
    };
  }
  let results = Belt_Array.map(arr, decodeDocument);
  let errors = Belt_Array.keep(results, result => result.TAG !== "Ok");
  if (errors.length !== 0) {
    return {
      TAG: "Error",
      _0: "Failed to decode some documents"
    };
  }
  let documents = Belt_Array.keepMap(results, result => {
    if (result.TAG === "Ok") {
      return result._0;
    }
  });
  return {
    TAG: "Ok",
    _0: documents
  };
}

function encodeDocument(doc) {
  let dict = {};
  dict["_id"] = doc._id;
  dict["title"] = doc.title;
  dict["ownerId"] = doc.ownerId;
  let content = doc.content;
  if (content !== undefined) {
    dict["content"] = content;
  } else {
    dict["content"] = null;
  }
  let role = doc.role;
  if (role !== undefined) {
    dict["role"] = role;
  } else {
    dict["role"] = null;
  }
  let date = doc.dateCreated;
  if (date !== undefined) {
    dict["dateCreated"] = date;
  }
  let date$1 = doc.lastModified;
  if (date$1 !== undefined) {
    dict["lastModified"] = date$1;
  }
  return dict;
}

function encodeDocumentCreateData(title, content, role) {
  let dict = {};
  dict["title"] = title;
  if (content !== undefined) {
    dict["content"] = content;
  }
  if (role !== undefined) {
    dict["role"] = role;
  }
  return dict;
}

function encodeDocumentUpdateData(title, content, role) {
  let dict = {};
  if (title !== undefined) {
    dict["title"] = title;
  }
  if (content !== undefined) {
    dict["content"] = content;
  }
  if (role !== undefined) {
    dict["role"] = role;
  }
  return dict;
}

export {
  decodeDocument,
  decodeDocumentList,
  encodeDocument,
  encodeDocumentCreateData,
  encodeDocumentUpdateData,
}
/* No side effect */
