// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function decodeDocument(json) {
  let obj = Js_json.decodeObject(json);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document object"
    };
  }
  let id = Js_dict.get(obj, "_id");
  let title = Js_dict.get(obj, "title");
  let content = Js_dict.get(obj, "content");
  let ownerId = Js_dict.get(obj, "ownerId");
  let role = Js_dict.get(obj, "role");
  let dateCreated = Js_dict.get(obj, "dateCreated");
  let lastModified = Js_dict.get(obj, "lastModified");
  if (id === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required document fields"
    };
  }
  if (title === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required document fields"
    };
  }
  if (ownerId === undefined) {
    return {
      TAG: "Error",
      _0: "Missing required document fields"
    };
  }
  let match = Js_json.decodeString(id);
  let match$1 = Js_json.decodeString(title);
  let match$2 = Js_json.decodeString(ownerId);
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document field types"
    };
  }
  if (match$1 === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document field types"
    };
  }
  if (match$2 === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document field types"
    };
  }
  let contentOpt = content !== undefined ? Js_json.decodeString(content) : undefined;
  let roleOpt;
  if (role !== undefined) {
    let match$3 = Js_json.decodeNull(role);
    roleOpt = match$3 !== undefined ? undefined : Js_json.decodeString(role);
  } else {
    roleOpt = undefined;
  }
  let dateCreatedOpt = dateCreated !== undefined ? Js_json.decodeString(dateCreated) : undefined;
  let lastModifiedOpt = lastModified !== undefined ? Js_json.decodeString(lastModified) : undefined;
  return {
    TAG: "Ok",
    _0: {
      _id: match,
      title: match$1,
      content: contentOpt,
      ownerId: match$2,
      role: roleOpt,
      dateCreated: dateCreatedOpt,
      lastModified: lastModifiedOpt
    }
  };
}

function decodeDocumentList(json) {
  let arr = Js_json.decodeArray(json);
  if (arr === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid document list array"
    };
  }
  let results = Belt_Array.map(arr, decodeDocument);
  let errors = Belt_Array.keep(results, result => result.TAG !== "Ok");
  if (errors.length !== 0) {
    return {
      TAG: "Error",
      _0: "Failed to decode some documents"
    };
  }
  let documents = Belt_Array.keepMap(results, result => {
    if (result.TAG === "Ok") {
      return result._0;
    }
  });
  return {
    TAG: "Ok",
    _0: documents
  };
}

function encodeDocument(doc) {
  let dict = {};
  dict["_id"] = doc._id;
  dict["title"] = doc.title;
  dict["ownerId"] = doc.ownerId;
  let content = doc.content;
  if (content !== undefined) {
    dict["content"] = content;
  } else {
    dict["content"] = null;
  }
  let role = doc.role;
  if (role !== undefined) {
    dict["role"] = role;
  } else {
    dict["role"] = null;
  }
  let date = doc.dateCreated;
  if (date !== undefined) {
    dict["dateCreated"] = date;
  }
  let date$1 = doc.lastModified;
  if (date$1 !== undefined) {
    dict["lastModified"] = date$1;
  }
  return dict;
}

function encodeDocumentCreateData(title, content, role) {
  let dict = {};
  dict["title"] = title;
  if (content !== undefined) {
    dict["content"] = content;
  }
  if (role !== undefined) {
    dict["role"] = role;
  }
  return dict;
}

function encodeDocumentUpdateData(title, content, role) {
  let dict = {};
  if (title !== undefined) {
    dict["title"] = title;
  }
  if (content !== undefined) {
    dict["content"] = content;
  }
  if (role !== undefined) {
    dict["role"] = role;
  }
  return dict;
}

export {
  decodeDocument,
  decodeDocumentList,
  encodeDocument,
  encodeDocumentCreateData,
  encodeDocumentUpdateData,
}
/* No side effect */
