// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Materialize from "../../bindings/Materialize.res.js";
import * as ReactRedux from "react-redux";
import * as LocalStorage from "../../bindings/LocalStorage.res.js";
import * as ReactRouterDom from "react-router-dom";
import * as AuthSlice from "../../features/auth/authSlice";

function logout(prim) {
  return AuthSlice.logout(prim);
}

function NavBar(props) {
  let reduxDispatch = ReactRedux.useDispatch();
  let navigate = ReactRouterDom.useNavigate();
  let user = ReactRedux.useSelector(store => store.auth.user);
  let session = ReactRedux.useSelector(store => store.auth.session);
  let logoutResult = ReactRedux.useSelector(store => store.auth.logoutResult);
  let match = React.useMemo(() => {
    let userId = user._id;
    let hasId = (userId == null) ? false : userId !== "";
    let sessionLoggedIn = session.loggedIn;
    let loggedIn = hasId && sessionLoggedIn;
    let name = user.name;
    let firstName;
    if (name == null) {
      firstName = "";
    } else {
      let first = name.first;
      firstName = (first == null) ? "" : first;
    }
    let role = user.role;
    let roleTitle;
    if (role == null) {
      roleTitle = "";
    } else {
      let title = role.title;
      roleTitle = (title == null) ? "" : title;
    }
    let isAdmin = roleTitle === "admin";
    return [
      loggedIn,
      firstName,
      isAdmin
    ];
  }, [
    user,
    session
  ]);
  let loggedIn = match[0];
  React.useEffect(() => {
    Materialize.initDropdown();
    Materialize.initSideNav();
  }, [loggedIn]);
  React.useEffect(() => {
    if (logoutResult !== "") {
      navigate("/");
    }
  }, [logoutResult]);
  let handleLogout = React.useCallback(evt => {
    evt.preventDefault();
    let token = LocalStorage.getItemOption("user");
    if (token !== undefined) {
      return reduxDispatch(AuthSlice.logout(token));
    }
  }, []);
  if (props.pathname === "/") {
    return null;
  }
  let renderNav = (function(loggedIn, userFirstName, isAdmin, handleLogout) {
        return (
          <nav className="transparent black-text" role="navigation">
            <div className="nav-wrapper container">
              <a 
                className="brand-logo brand-logo-small"
                href={loggedIn ? "/dashboard" : "/"}
              >
                <img alt="Docue Logo" id="header-logo" src="/favicon.png" />
                {"      Docue"}
              </a>
              <a 
                href="#" 
                data-activates="mobile-demo" 
                className="button-collapse"
              >
                <i className="material-icons" style={{color: 'grey'}}>
                  menu
                </i>
              </a>
              
              <ul className="side-nav" id="mobile-demo">
                <li>
                  <a href="/">Home</a>
                </li>
                <li>
                  {loggedIn ? (
                    <a href="/profile">Profile</a>
                  ) : (
                    <a href="/auth">Login</a>
                  )}
                </li>
                <li>
                  {loggedIn ? (
                    <a href="#" onClick={handleLogout}>Logout</a>
                  ) : (
                    <a href="/auth">Sign Up</a>
                  )}
                </li>
              </ul>
              
              <ul className="right hide-on-med-and-down" id="nav-mobile">
                <li>
                  {loggedIn ? (
                    <div>
                      <ul id="dropdown" className="dropdown-content">
                        <li>
                          <a href="/profile">My Profile</a>
                        </li>
                        <li>
                          <a href="/dashboard">All Documents</a>
                        </li>
                        {isAdmin ? (
                          <li>
                            <a href="/admin">Settings</a>
                          </li>
                        ) : null}
                        <li className="divider"></li>
                        <li>
                          <a href="#" id="logout-btn" onClick={handleLogout}> Logout</a>
                        </li>
                      </ul>
                      <a 
                        className="dropdown-button"
                        data-activates="dropdown"
                        data-beloworigin="true"
                        data-constrainwidth="false"
                      >
                        {userFirstName}
                        <i className="material-icons right">arrow_drop_down</i>
                      </a>
                    </div>
                  ) : null}
                </li>
              </ul>
            </div>
          </nav>
        );
      });
  return renderNav(loggedIn, match[1], match[2], handleLogout);
}

let make = NavBar;

let $$default = NavBar;

export {
  logout,
  make,
  $$default as default,
}
/* react Not a pure module */
