// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Materialize from "../../bindings/Materialize.res.js";
import * as ReactRedux from "react-redux";
import * as LocalStorage from "../../bindings/LocalStorage.res.js";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as MaterializeHelpers from "./MaterializeHelpers";
import * as AuthSlice from "../../features/auth/authSlice";

function logout(prim) {
  return AuthSlice.logout(prim);
}

function createDropdownButton(prim0, prim1) {
  return MaterializeHelpers.createDropdownButton(prim0, prim1);
}

function createMobileMenuButton(prim) {
  return MaterializeHelpers.createMobileMenuButton(prim);
}

function NavBar(props) {
  let reduxDispatch = ReactRedux.useDispatch();
  let navigate = ReactRouterDom.useNavigate();
  let user = ReactRedux.useSelector(store => store.auth.user);
  let session = ReactRedux.useSelector(store => store.auth.session);
  let logoutResult = ReactRedux.useSelector(store => store.auth.logoutResult);
  let match = React.useMemo(() => {
    let userId = user._id;
    let hasId = (userId == null) ? false : userId !== "";
    let sessionLoggedIn = session.loggedIn;
    let loggedIn = hasId && sessionLoggedIn;
    let name = user.name;
    let firstName;
    if (name == null) {
      firstName = "";
    } else {
      let first = name.first;
      firstName = (first == null) ? "" : first;
    }
    let role = user.role;
    let roleTitle;
    if (role == null) {
      roleTitle = "";
    } else {
      let title = role.title;
      roleTitle = (title == null) ? "" : title;
    }
    let isAdmin = roleTitle === "admin";
    return [
      loggedIn,
      firstName,
      isAdmin
    ];
  }, [
    user,
    session
  ]);
  let loggedIn = match[0];
  React.useEffect(() => {
    Materialize.initDropdown();
    Materialize.initSideNav();
  }, [loggedIn]);
  React.useEffect(() => {
    if (logoutResult !== "") {
      navigate("/");
    }
  }, [logoutResult]);
  let handleLogout = React.useCallback(evt => {
    evt.preventDefault();
    let token = LocalStorage.getItemOption("user");
    if (token !== undefined) {
      return reduxDispatch(AuthSlice.logout(token));
    }
  }, []);
  if (props.pathname === "/") {
    return null;
  } else {
    return JsxRuntime.jsx("nav", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs(ReactRouterDom.Link, {
            to: loggedIn ? "/dashboard" : "/",
            className: "brand-logo brand-logo-small",
            children: [
              JsxRuntime.jsx("img", {
                id: "header-logo",
                alt: "Docue Logo",
                src: "/favicon.png"
              }),
              "Docue"
            ]
          }),
          JsxRuntime.jsx(React.Fragment, {
            children: MaterializeHelpers.createMobileMenuButton(evt => {
              evt.preventDefault();
            })
          }),
          JsxRuntime.jsxs("ul", {
            children: [
              JsxRuntime.jsx("li", {
                children: JsxRuntime.jsx(ReactRouterDom.Link, {
                  to: "/",
                  children: "Home"
                })
              }),
              JsxRuntime.jsx("li", {
                children: loggedIn ? JsxRuntime.jsx(ReactRouterDom.Link, {
                    to: "/profile",
                    children: "Profile"
                  }) : JsxRuntime.jsx(ReactRouterDom.Link, {
                    to: "/auth",
                    children: "Login"
                  })
              }),
              JsxRuntime.jsx("li", {
                children: loggedIn ? JsxRuntime.jsx("a", {
                    children: "Logout",
                    href: "#",
                    onClick: handleLogout
                  }) : JsxRuntime.jsx(ReactRouterDom.Link, {
                    to: "/auth",
                    children: "Sign Up"
                  })
              })
            ],
            className: "side-nav",
            id: "mobile-demo"
          }),
          JsxRuntime.jsx("ul", {
            children: JsxRuntime.jsx("li", {
              children: loggedIn ? JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                          children: JsxRuntime.jsx(ReactRouterDom.Link, {
                            to: "/profile",
                            children: "My Profile"
                          })
                        }),
                        JsxRuntime.jsx("li", {
                          children: JsxRuntime.jsx(ReactRouterDom.Link, {
                            to: "/dashboard",
                            children: "All Documents"
                          })
                        }),
                        match[2] ? JsxRuntime.jsx("li", {
                            children: JsxRuntime.jsx(ReactRouterDom.Link, {
                              to: "/admin",
                              children: "Settings"
                            })
                          }) : null,
                        JsxRuntime.jsx("li", {
                          className: "divider"
                        }),
                        JsxRuntime.jsx("li", {
                          children: JsxRuntime.jsx("a", {
                            children: " Logout",
                            id: "logout-btn",
                            href: "#",
                            onClick: handleLogout
                          })
                        })
                      ],
                      className: "dropdown-content",
                      id: "dropdown"
                    }),
                    JsxRuntime.jsx(React.Fragment, {
                      children: MaterializeHelpers.createDropdownButton(match[1], evt => {
                        evt.preventDefault();
                      })
                    })
                  ]
                }) : null
            }),
            className: "right hide-on-med-and-down",
            id: "nav-mobile"
          })
        ],
        className: "nav-wrapper container"
      }),
      className: "transparent black-text",
      role: "navigation"
    });
  }
}

let make = NavBar;

let $$default = NavBar;

export {
  logout,
  createDropdownButton,
  createMobileMenuButton,
  make,
  $$default as default,
}
/* react Not a pure module */
