// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";

function decodeRole(json) {
  let obj = Stdlib_JSON.Decode.object(json);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid role object"
    };
  }
  let id = obj["_id"];
  let title = obj["title"];
  let accessLevel = obj["accessLevel"];
  if (id === undefined) {
    return {
      TAG: "Error",
      _0: "Missing role fields"
    };
  }
  if (title === undefined) {
    return {
      TAG: "Error",
      _0: "Missing role fields"
    };
  }
  if (accessLevel === undefined) {
    return {
      TAG: "Error",
      _0: "Missing role fields"
    };
  }
  let match = Stdlib_JSON.Decode.string(id);
  let match$1 = Stdlib_JSON.Decode.string(title);
  let match$2 = Stdlib_JSON.Decode.float(accessLevel);
  if (match !== undefined && match$1 !== undefined && match$2 !== undefined) {
    return {
      TAG: "Ok",
      _0: {
        _id: match,
        title: match$1,
        accessLevel: match$2 | 0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: "Invalid role field types"
    };
  }
}

function decodeRoleList(json) {
  let arr = Stdlib_JSON.Decode.array(json);
  if (arr === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid role list array"
    };
  }
  let results = Belt_Array.map(arr, decodeRole);
  let errors = Belt_Array.keep(results, result => result.TAG !== "Ok");
  if (errors.length !== 0) {
    return {
      TAG: "Error",
      _0: "Failed to decode some roles"
    };
  }
  let roles = Belt_Array.keepMap(results, result => {
    if (result.TAG === "Ok") {
      return result._0;
    }
  });
  return {
    TAG: "Ok",
    _0: roles
  };
}

function encodeRole(role) {
  let dict = {};
  dict["_id"] = role._id;
  dict["title"] = role.title;
  dict["accessLevel"] = role.accessLevel;
  return dict;
}

function encodeRoleCreateData(title) {
  let dict = {};
  dict["title"] = title;
  return dict;
}

function toString(level) {
  switch (level) {
    case 0 :
      return "viewer";
    case 1 :
      return "staff";
    case 2 :
      return "admin";
    default:
      return "unknown";
  }
}

function fromString(str) {
  switch (str) {
    case "admin" :
      return 2;
    case "staff" :
      return 1;
    case "viewer" :
      return 0;
    default:
      return;
  }
}

let AccessLevel = {
  viewer: 0,
  staff: 1,
  admin: 2,
  toString: toString,
  fromString: fromString
};

export {
  decodeRole,
  decodeRoleList,
  encodeRole,
  encodeRoleCreateData,
  AccessLevel,
}
/* No side effect */
