// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fetch from "../../bindings/Fetch.res.js";
import * as React from "react";
import * as LocalStorage from "../../bindings/LocalStorage.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function getBaseUrl() {
  let match = process.env.NODE_ENV;
  if (match === "development") {
    return "http://localhost:8000";
  } else {
    return "https://docue.herokuapp.com";
  }
}

function decodeStats(_json) {
  try {
    let documents = (_json.documents || 0);
    let users = (_json.users || 0);
    let roles = (_json.roles || 0);
    return {
      TAG: "Ok",
      _0: {
        documents: documents,
        users: users,
        roles: roles
      }
    };
  } catch (exn) {
    return {
      TAG: "Error",
      _0: "Failed to decode stats"
    };
  }
}

async function fetchStats(token) {
  try {
    let baseUrl = getBaseUrl();
    let url = baseUrl + "/api/stats";
    let response = await Fetch.get(url, token);
    if (response.ok) {
      return decodeStats(await response.json());
    } else {
      return {
        TAG: "Error",
        _0: "Failed to fetch stats: HTTP " + response.status.toString()
      };
    }
  } catch (exn) {
    return {
      TAG: "Error",
      _0: "Network error occurred"
    };
  }
}

function Admin(props) {
  let match = React.useState(() => "Loading");
  let setState = match[1];
  let state = match[0];
  React.useEffect(() => {
    let token = LocalStorage.getItemOption("user");
    if (token !== undefined) {
      let loadStats = async () => {
        let result = await fetchStats(token);
        if (result.TAG === "Ok") {
          let stats = result._0;
          return setState(param => ({
            TAG: "Loaded",
            _0: stats
          }));
        }
        let msg = result._0;
        return setState(param => ({
          TAG: "Error",
          _0: msg
        }));
      };
      loadStats();
    } else {
      setState(param => ({
        TAG: "Error",
        _0: "No authentication token found"
      }));
    }
  }, []);
  if (typeof state !== "object") {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Admin Panel",
            className: "header center-align"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("p", {
                children: "Loading statistics...",
                className: "flow-text"
              }),
              className: "col s12 center-align"
            }),
            className: "row"
          })
        ],
        className: "card-panel"
      }),
      className: "container"
    });
  }
  if (state.TAG !== "Loaded") {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Admin Panel",
            className: "header center-align"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("p", {
                children: "Error: " + state._0,
                className: "flow-text red-text"
              }),
              className: "col s12 center-align"
            }),
            className: "row"
          })
        ],
        className: "card-panel"
      }),
      className: "container"
    });
  }
  let stats = state._0;
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h2", {
          children: "Admin Panel",
          className: "header center-align"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h5", {
                  children: "Total Users"
                }),
                JsxRuntime.jsx("p", {
                  children: stats.users.toString(),
                  className: "flow-text",
                  id: "users-count"
                }),
                JsxRuntime.jsxs("a", {
                  children: [
                    JsxRuntime.jsx("i", {
                      children: "face",
                      className: "material-icons left"
                    }),
                    "Manage Users"
                  ],
                  className: "waves-effect waves-light btn blue",
                  href: "/admin/users"
                })
              ],
              className: "col s4 center-align"
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h5", {
                  children: "Total Documents"
                }),
                JsxRuntime.jsx("p", {
                  children: stats.documents.toString(),
                  className: "flow-text",
                  id: "docs-count"
                }),
                JsxRuntime.jsxs("a", {
                  children: [
                    JsxRuntime.jsx("i", {
                      children: "drafts",
                      className: "material-icons left"
                    }),
                    "Manage Docs"
                  ],
                  className: "waves-effect waves-light btn blue",
                  href: "/dashboard"
                })
              ],
              className: "col s4 center-align"
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h5", {
                  children: "Total Roles"
                }),
                JsxRuntime.jsx("p", {
                  children: stats.roles.toString(),
                  className: "flow-text",
                  id: "roles-count"
                }),
                JsxRuntime.jsxs("a", {
                  children: [
                    JsxRuntime.jsx("i", {
                      children: "settings",
                      className: "material-icons left"
                    }),
                    "Manage Roles"
                  ],
                  className: "waves-effect waves-light btn blue",
                  href: "/admin/roles"
                })
              ],
              className: "col s4 center-align"
            })
          ],
          className: "row"
        })
      ],
      className: "card-panel"
    }),
    className: "container"
  });
}

let make = Admin;

let $$default = Admin;

export {
  getBaseUrl,
  decodeStats,
  fetchStats,
  make,
  $$default as default,
}
/* react Not a pure module */
