// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Materialize from "../../bindings/Materialize.res.js";
import * as ReactRedux from "react-redux";
import * as LocalStorage from "../../bindings/LocalStorage.res.js";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as RolesSlice from "../../features/roles/rolesSlice";

function createRole(prim) {
  return RolesSlice.createRole(prim);
}

function reducer(state, action) {
  if (typeof action === "object") {
    return {
      title: action._0,
      createAttempted: state.createAttempted
    };
  }
  switch (action) {
    case "Submit" :
      return state;
    case "CreateAttempted" :
      return {
        title: state.title,
        createAttempted: true
      };
    case "ResetAttempt" :
      return {
        title: state.title,
        createAttempted: false
      };
  }
}

let initialState = {
  title: "",
  createAttempted: false
};

function CreateRole(props) {
  let match = React.useReducer(reducer, initialState);
  let dispatch = match[1];
  let state = match[0];
  let reduxDispatch = ReactRedux.useDispatch();
  let navigate = ReactRouterDom.useNavigate();
  let t = LocalStorage.getItemOption("user");
  let token = t !== undefined ? t : "";
  let createdRole = ReactRedux.useSelector(store => store.roles.createdRole);
  let error = ReactRedux.useSelector(store => store.roles.error);
  let handleSubmit = evt => {
    evt.preventDefault();
    if (state.title === "") {
      return Materialize.showError("Please Provide a Role Title");
    }
    dispatch("CreateAttempted");
    let roleData = {
      title: state.title
    };
    let payload = {
      data: roleData,
      token: token
    };
    reduxDispatch(RolesSlice.createRole(payload));
  };
  React.useEffect(() => {
    if (state.createAttempted) {
      let isNull = (createdRole === null);
      if (!isNull) {
        Materialize.showSuccess("Role created successfully!");
        navigate("/admin/roles");
        dispatch("ResetAttempt");
      }
    }
  }, [
    createdRole,
    state.createAttempted
  ]);
  React.useEffect(() => {
    if (state.createAttempted) {
      let hasError = (error && error !== "");
      if (hasError) {
        Materialize.showError(error);
        dispatch("ResetAttempt");
      }
    }
  }, [
    error,
    state.createAttempted
  ]);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("h2", {
          children: "Create Role",
          className: "header center-align"
        }),
        className: "row"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("form", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("input", {
                  className: "validate",
                  id: "title",
                  name: "title",
                  type: "text",
                  value: state.title,
                  onChange: evt => {
                    let value = evt.target.value;
                    dispatch({
                      TAG: "UpdateTitle",
                      _0: value
                    });
                  }
                }),
                JsxRuntime.jsx("label", {
                  children: "Title",
                  className: "active",
                  htmlFor: "title"
                })
              ],
              className: "input-field col s4 offset-s2"
            }),
            JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("button", {
                children: [
                  "submit",
                  JsxRuntime.jsx("i", {
                    children: "send",
                    className: "material-icons right"
                  })
                ],
                className: "btn waves-effect header-btn blue",
                style: {top: "25px", position: "relative"},
                name: "action",
                type: "submit"
              }),
              className: "col s6"
            })
          ],
          className: "col s12",
          onSubmit: handleSubmit
        }),
        className: "row"
      })
    ],
    className: "container"
  });
}

let make = CreateRole;

let $$default = CreateRole;

export {
  createRole,
  reducer,
  initialState,
  make,
  $$default as default,
}
/* react Not a pure module */
