// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Landing(props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("div", {
            children: JsxRuntime.jsxs("h1", {
              children: [
                JsxRuntime.jsx("span", {
                  children: "Docue    ",
                  className: "bold"
                }),
                JsxRuntime.jsx("span", {
                  children: "is the simplest way for",
                  className: "thin"
                }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("span", {
                  children: "you to manage your documents online",
                  className: "thin"
                })
              ],
              id: "hero-title"
            }),
            className: "col s12 center-align"
          }),
          className: "row"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("a", {
                children: "Get Started",
                className: "btn btn-large create-list-link hero-btn",
                href: "/auth"
              }),
              className: "center-align"
            }),
            className: "col s12"
          }),
          className: "row"
        })
      ],
      className: "container",
      id: "hero-text-container"
    }),
    id: "hero"
  });
}

let make = Landing;

let $$default = Landing;

export {
  make,
  $$default as default,
}
/* react/jsx-runtime Not a pure module */
