services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      APP_ENV: prod
      SQLITE_FILE: /data/docue.db
    volumes:
      - sqlite-data:/data

volumes:
  sqlite-data:
