// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Materialize from "../../bindings/Materialize.res.js";
import * as ReactRedux from "react-redux";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as AuthSlice from "../../features/auth/authSlice";

function signup(prim) {
  return AuthSlice.signup(prim);
}

function validatePassword(password, passwordConfirm) {
  if (password !== passwordConfirm) {
    return "Mismatch";
  } else if (password.length >= 1 && password.length < 6) {
    return "TooShort";
  } else {
    return "Valid";
  }
}

function reducer(state, action) {
  if (typeof action !== "object") {
    switch (action) {
      case "Submit" :
        return state;
      case "SignupAttempted" :
        return {
          firstname: state.firstname,
          lastname: state.lastname,
          email: state.email,
          password: state.password,
          passwordConfirm: state.passwordConfirm,
          signupAttempted: true
        };
      case "ResetAttempt" :
        return {
          firstname: state.firstname,
          lastname: state.lastname,
          email: state.email,
          password: state.password,
          passwordConfirm: state.passwordConfirm,
          signupAttempted: false
        };
    }
  } else {
    switch (action.TAG) {
      case "UpdateFirstname" :
        return {
          firstname: action._0,
          lastname: state.lastname,
          email: state.email,
          password: state.password,
          passwordConfirm: state.passwordConfirm,
          signupAttempted: state.signupAttempted
        };
      case "UpdateLastname" :
        return {
          firstname: state.firstname,
          lastname: action._0,
          email: state.email,
          password: state.password,
          passwordConfirm: state.passwordConfirm,
          signupAttempted: state.signupAttempted
        };
      case "UpdateEmail" :
        return {
          firstname: state.firstname,
          lastname: state.lastname,
          email: action._0,
          password: state.password,
          passwordConfirm: state.passwordConfirm,
          signupAttempted: state.signupAttempted
        };
      case "UpdatePassword" :
        return {
          firstname: state.firstname,
          lastname: state.lastname,
          email: state.email,
          password: action._0,
          passwordConfirm: state.passwordConfirm,
          signupAttempted: state.signupAttempted
        };
      case "UpdatePasswordConfirm" :
        return {
          firstname: state.firstname,
          lastname: state.lastname,
          email: state.email,
          password: state.password,
          passwordConfirm: action._0,
          signupAttempted: state.signupAttempted
        };
    }
  }
}

let initialState = {
  firstname: "",
  lastname: "",
  email: "",
  password: "",
  passwordConfirm: "",
  signupAttempted: false
};

function SignUp(props) {
  let match = React.useReducer(reducer, initialState);
  let dispatch = match[1];
  let state = match[0];
  let reduxDispatch = ReactRedux.useDispatch();
  let navigate = ReactRouterDom.useNavigate();
  let signupError = ReactRedux.useSelector(store => store.auth.signupError);
  let token = ReactRedux.useSelector(store => store.auth.token);
  let user = ReactRedux.useSelector(store => store.auth.user);
  let session = ReactRedux.useSelector(store => store.auth.session);
  let handleSubmit = evt => {
    evt.preventDefault();
    let match = validatePassword(state.password, state.passwordConfirm);
    switch (match) {
      case "Valid" :
        dispatch("SignupAttempted");
        let payload = {
          firstname: state.firstname,
          lastname: state.lastname,
          username: state.email,
          email: state.email,
          password: state.password
        };
        return reduxDispatch(AuthSlice.signup(payload));
      case "Mismatch" :
        return Materialize.showError("passwords don't match");
      case "TooShort" :
        return Materialize.showError("passwords should be > 6 characters");
    }
  };
  React.useEffect(() => {
    if (state.signupAttempted) {
      let errorIsNull = (signupError === null || signupError === undefined);
      if (!errorIsNull) {
        let isObject = (typeof signupError === "object");
        let errorMessage;
        if (isObject) {
          let hasErrorProp = (errorObj.error !== null && errorObj.error !== undefined);
          errorMessage = hasErrorProp ? signupError.error : signupError;
        } else {
          errorMessage = signupError;
        }
        Materialize.showError(errorMessage);
        dispatch("ResetAttempt");
      }
      let loggedIn = session.loggedIn;
      if (token !== "" && loggedIn) {
        localStorage.setItem("user", token);
        let userJson = (JSON.stringify(user));
        localStorage.setItem("userInfo", userJson);
        Materialize.showSuccess("Your Account has been created successfully!");
        navigate("/dashboard");
        dispatch("ResetAttempt");
      }
    }
  }, [
    signupError,
    token,
    user,
    session,
    state.signupAttempted
  ]);
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("form", {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "validate",
              id: "firstname",
              name: "firstname",
              required: true,
              type: "text",
              onChange: evt => {
                let value = evt.target.value;
                dispatch({
                  TAG: "UpdateFirstname",
                  _0: value
                });
              }
            }),
            JsxRuntime.jsx("label", {
              children: "First Name",
              htmlFor: "firstname"
            })
          ],
          className: "input-field col m6 s12"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "validate",
              id: "lastname",
              name: "lastname",
              required: true,
              type: "text",
              onChange: evt => {
                let value = evt.target.value;
                dispatch({
                  TAG: "UpdateLastname",
                  _0: value
                });
              }
            }),
            JsxRuntime.jsx("label", {
              children: "Last Name",
              htmlFor: "lastname"
            })
          ],
          className: "input-field col m6 s12"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "validate",
              id: "email",
              name: "email",
              required: true,
              type: "email",
              onChange: evt => {
                let value = evt.target.value;
                dispatch({
                  TAG: "UpdateEmail",
                  _0: value
                });
              }
            }),
            JsxRuntime.jsx("label", {
              children: "Email",
              htmlFor: "email"
            })
          ],
          className: "input-field col s12"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "validate",
              id: "password",
              name: "password",
              required: true,
              type: "password",
              onChange: evt => {
                let value = evt.target.value;
                dispatch({
                  TAG: "UpdatePassword",
                  _0: value
                });
              }
            }),
            JsxRuntime.jsx("label", {
              children: "Password",
              htmlFor: "password"
            })
          ],
          className: "input-field col s12"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "validate",
              id: "password-confirm",
              name: "password-confirm",
              required: true,
              type: "password",
              onChange: evt => {
                let value = evt.target.value;
                dispatch({
                  TAG: "UpdatePasswordConfirm",
                  _0: value
                });
              }
            }),
            JsxRuntime.jsx("label", {
              children: "Confirm Password",
              htmlFor: "password-confirm"
            })
          ],
          className: "input-field col s12"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("button", {
              children: "Sign up",
              className: "btn waves-effect waves-light blue",
              name: "action",
              type: "submit"
            }),
            className: "center"
          }),
          className: "col s12"
        })
      ],
      className: "col s12",
      onSubmit: handleSubmit
    }),
    className: "row"
  });
}

let make = SignUp;

let $$default = SignUp;

export {
  signup,
  validatePassword,
  reducer,
  initialState,
  make,
  $$default as default,
}
/* react Not a pure module */
